// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SyncfusionBlazorApp1.Models;

public partial class Building
{
    public int BuildingId { get; set; }

    public int CampusId { get; set; }

    public string BuildingName { get; set; }

    public int NoOfRooms { get; set; }

    public int NoOfMeetingHalls { get; set; }

    public bool isLibrary { get; set; }

    public int NoOfComputerLabs { get; set; }

    public int NoOfTerminals { get; set; }

    public virtual Campus Campus { get; set; }

    public virtual ICollection<Room> Room { get; set; } = new List<Room>();
}