// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SyncfusionBlazorApp1.Models;

public partial class City
{
    public int CityId { get; set; }

    public int StateId { get; set; }

    public string CityName { get; set; }

    public virtual ICollection<Campus> Campus { get; set; } = new List<Campus>();

    public virtual ICollection<Faculty> Faculty { get; set; } = new List<Faculty>();

    public virtual State State { get; set; }

    public virtual ICollection<Student> Student { get; set; } = new List<Student>();

    public virtual ICollection<University> University { get; set; } = new List<University>();
}