// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SyncfusionBlazorApp1.Models;

public partial class Country
{
    public int CountryId { get; set; }

    public string CountryName { get; set; }

    public virtual ICollection<Campus> Campus { get; set; } = new List<Campus>();

    public virtual ICollection<Faculty> Faculty { get; set; } = new List<Faculty>();

    public virtual ICollection<State> State { get; set; } = new List<State>();

    public virtual ICollection<Student> Student { get; set; } = new List<Student>();

    public virtual ICollection<University> University { get; set; } = new List<University>();
}