// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SyncfusionBlazorApp1.Models;

public partial class Designation
{
    public int DesignationId { get; set; }

    public string Name { get; set; }

    public virtual ICollection<Faculty> Faculty { get; set; } = new List<Faculty>();
}