// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SyncfusionBlazorApp1.Models;

public partial class FeeMaster
{
    public int FeeMasterId { get; set; }

    public int SemesterCourseId { get; set; }

    public int FeeAmount { get; set; }

    public virtual SemesterCourse SemesterCourse { get; set; }
}