// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SyncfusionBlazorApp1.Models;

public partial class Room
{
    public int RoomId { get; set; }

    public int BuildingId { get; set; }

    public string RoomName { get; set; }

    public bool isLibrary { get; set; }

    public bool isComputerLab { get; set; }

    public bool isOtherLab { get; set; }

    public int Capacity { get; set; }

    public virtual Building Building { get; set; }

    public virtual ICollection<SemesterCourse> SemesterCourse { get; set; } = new List<SemesterCourse>();
}