// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SyncfusionBlazorApp1.Models;

public partial class StudentSemesterCourse
{
    public int StudentSemesterCourseId { get; set; }

    public int SemesterCourseId { get; set; }

    public int StudentId { get; set; }

    public virtual SemesterCourse SemesterCourse { get; set; }

    public virtual Student Student { get; set; }
}