// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SyncfusionBlazorApp1.Models;

public partial class User
{
    public int UserId { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public string Mail { get; set; }

    public virtual ICollection<Faculty> Faculty { get; set; } = new List<Faculty>();

    public virtual ICollection<Student> Student { get; set; } = new List<Student>();
}